on:
  push:
    branches:
      - main

jobs:
  Release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          persist-credentials: false
      - uses: actions/setup-node@v2.4.0
        with:
          node-version: 14
      - run: |
          npm install @semantic-release/git -D
          npm install @semantic-release/changelog -D
      - run: npx semantic-release
        env:
          GH_TOKEN: ${{ secrets.RELEASE_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.github_token }}

  Publish:
    needs: Release

    runs-on: ubuntu-latest

    environment: Production

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
    
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      
      - uses: WyriHaximus/github-action-get-previous-tag@v1
        id: latest_tag
        with:
          fallback: 0.0.1

      - run: |
            pip install poetry
            poetry version ${{ steps.latest_tag.outputs.tag }}
            poetry build
            poetry config pypi-token.pypi ${{ secrets.PYPI_KEY }}
            poetry publish --username __token__
